# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Backtrack <- function(RCV, end) {
    .Call('_dbh_Backtrack', PACKAGE = 'dbh', RCV, end)
}

RejsBH <- function(posit, sgn, RCV, avals) {
    .Call('_dbh_RejsBH', PACKAGE = 'dbh', posit, sgn, RCV, avals)
}

